### ISSUE TITLE
got broken url message but there are no urls listed

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/ottr-reports#11]
https://github.com/fhdsl/NIH_Data_Sharing/pull/23

Doing this pull request I first had a broken url (really it wasn't but it had a space between the brackets and parentheses). 

No after fixing that it still says broken urls but the report lists no urls.
![Screen Shot 2022-10-27 at 11 55 30 AM](https://user-images.githubusercontent.com/23014755/198339408-74451094-eabc-47d3-af04-786be5731717.png)

![Screen Shot 2022-10-27 at 11 55 05 AM](https://user-images.githubusercontent.com/23014755/198339274-4d3d592a-6cb1-4896-9cee-009354e89d3e.png)

So I guess the message just didn't update with the report change maybe?

**Comment by cansavvy** [comment]
The commitID reported should be able to let you know if the report is the latest. But we could add a time stamp since that might be easier to read. We don't really have control over GitHub page refreshing stuff.

**Comment by carriewright11** [comment]
right, or just tell people to refresh if things look confusing? I like the time stamp idea if that isn't too difficult - but I wonder if people will notice

**Comment by cansavvy** [comment]
Both is good

**Comment by carriewright11** [comment]
sounds good to me!

**Comment by carriewright11** [comment]
I can work on the documentation
