### ISSUE TITLE
url-check flags urls when they're parenthetical

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/ottr-reports#17]
### Problem:

In one of my books, I've got a url listed in parentheses, like this:
```
 using the `swirl` package (https://swirlstats.com), which teaches students ...
```

The url checker reports this as broken because it grabs the closing parenthesis and comma like so:
`https://swirlstats.com),`

I could add it to my ignore file, but since this a url I'm linking to, it'd be nice if it got checked.  And sticking a url in parentheses seems like something other people might want to do sometimes.

### Here's the PR I'm working on

https://github.com/jhudsl/GDSCN_Book_swirl/pull/26

We just got AnVIL_Template caught up to OTTR, and this PR is passing those updates on to my book.  If I understand things correctly, I believe that means this PR is using the latest version of url check (i.e. the version in the PR, not the version in `main`)?

**Comment by avahoffman** [comment]
Resolved by https://github.com/jhudsl/ottr-reports/pull/18

FYI @KatherineCox , please keep an eye on this in case I introduced a bug instead :)

**Comment by KatherineCox** [comment]
Woot!  Thanks @avahoffman!

**Comment by KatherineCox** [comment]
@avahoffman 

I'm not quite sure how things propagate from here through to AnVIL_Template - if I run a PR render right now in one of the AnVIL books does it use the most recent version of this `ottr-reports` action?  Or do we need to update something in AnVIL_Template and send out a sync?

I've got another parenthetical URL with a slightly different form that's getting flagged in AnVIL_Instructor_Guide, but I don't know if it's using your updated version of the action:

### Problem URL:
`...makes it easier to incorporate version control (e.g., using [git](https://git-scm.com/)) and ensures...`
Flagged as:
`https://git-scm.com/)`

### PR link
PR is here: https://github.com/jhudsl/AnVIL_Book_Instructor_Guide/pull/96
FYI, this PR is weird because we sent out updates from AnVIL_Template while it was open, so there are two copies of the URL comment - the one at the top of the PR is out of date, the one waaaaaay down the page (March 30) is the one that gets updated when the PR actions run.

**Comment by avahoffman** [comment]
@KatherineCox  Each time the action is run in one of the course repos, it pulls from `main` here in ottr-reports (line [here](https://github.com/jhudsl/AnVIL_Book_Instructor_Guide/blob/4ce5d05fda2d15d0064d7c9311157274f54f8d43/.github/workflows/pull_request.yml#L67)).. so no syncing needed :)

Let me see if I can reproduce this exception and write some code for it in a new PR.
