### ISSUE TITLE
spell-checking all markdown files?

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/ottr-reports#28]
Hey @cansavvy I've suddenly got a bunch of new spelling errors coming from my README, LICENSE, CONTRIBUTING files, and the About pages, which weren't previously being checked.  Is that the plan going forward?  Or are you going to exclude any of those?

Wondering if I should go start updating my `dictionary.txt` files, or just wait it out.

**Comment by cansavvy** [comment]
We can add an "exclude_files.txt" feature that allows files to be ignored.

There's been growing interest in having OTTR compatible with Qmd and md files so I switched that on. Sorry it's caused some issues.

Would the above be a good solution for you?

**Comment by KatherineCox** [comment]
`exclude_files.txt` would be great, thanks!
