### ISSUE TITLE
Up the doc game here

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/ottr-reports#31]
We need more docs here that explain how this works so people can contribute. 

Here's the basics: 

1. `main.sh` is the core of the action it is called by `action.yml`
2. `main.sh` copies over and runs the scripts in the `scripts` folder
3. `report-maker.yml` calls `action.yml` and handles the commenting on the PRs.

**Comment by howardbaik** [comment]
Addressed in https://github.com/jhudsl/ottr-reports/pull/35
